### PR TITLE
Update whitelist.json

### PR DESCRIPTION
**Pull request by JacKingt0n**
### Description of the project
Sora's best friend
### Website or public page of the project
http://sora.dog
### What is the name of the token you are adding? 
SOSHIBA
### Notes or questions to developers [optional]
Submitting this for Yannis

### CODE REVIEW

**Comment by stefashkaa** [comment]
@JacKingt0n hello! Thanks for PR, but you need to provide an icon

**Comment by JacKingt0n** [comment]
> @JacKingt0n hello! Thanks for PR, but you need to provide an icon

Hi the icon URI is in there in png format (Zilya had recommend PNG format)
I see it in the commit  here is a screenshot and it appears to decode OK?
2021-06-29-000551_5760x2160_scrot

**Comment by JacKingt0n** [comment]
if any issues with my uri code, here's the PNG 
LOGO-SS2

**Comment by iamexe** [comment]
> @JacKingt0n hello! Thanks for PR, but you need to provide an icon

when whitelist? :)

**Comment by iamexe** [comment]
This pull request was replaced with this one: 
https://github.com/sora-xor/polkaswap-token-whitelist-config/pull/8

**Comment by stefashkaa** [comment]
@iamexe Hello! Ok, so, I'll close this PR and merge #8

**Pull request closed without merging**
